In [1]:
import pandas as pd
import re

In [5]:
df = pd.read_csv("/content/sample_data/Orca_Math_Problems.csv")

ParserError: Error tokenizing data. C error: Expected 2 fields in line 3685, saw 3

In [9]:
df = pd.read_csv("/content/sample_data/Orca_Math_Problems.csv", on_bad_lines='warn')

/tmp/ipython-input-9-300422090.py:1: ParserWarning: Skipping line 3685: expected 2 fields, saw 3
Skipping line 6023: expected 2 fields, saw 3
Skipping line 9294: expected 2 fields, saw 3
Skipping line 14381: expected 2 fields, saw 3
Skipping line 18429: expected 2 fields, saw 3
Skipping line 23477: expected 2 fields, saw 3
Skipping line 24450: expected 2 fields, saw 5
Skipping line 35498: expected 2 fields, saw 3
Skipping line 35500: expected 2 fields, saw 3
Skipping line 36467: expected 2 fields, saw 4
Skipping line 45379: expected 2 fields, saw 3
Skipping line 53375: expected 2 fields, saw 3
Skipping line 61202: expected 2 fields, saw 3
Skipping line 69976: expected 2 fields, saw 3
Skipping line 80833: expected 2 fields, saw 3
Skipping line 90395: expected 2 fields, saw 3
Skipping line 94939: expected 2 fields, saw 3
Skipping line 95915: expected 2 fields, saw 3
Skipping line 96788: expected 2 fields, saw 3
Skipping line 96815: expected 2 fields, saw 3
Skipping line 98648: expected 2 fields, saw 3
Skipping line 101398: expected 2 fields, saw 3
Skipping line 104110: expected 2 fields, saw 3
Skipping line 108632: expected 2 fields, saw 3
Skipping line 117678: expected 2 fields, saw 3
Skipping line 120369: expected 2 fields, saw 3
Skipping line 123928: expected 2 fields, saw 3
Skipping line 127501: expected 2 fields, saw 3
Skipping line 129313: expected 2 fields, saw 3
Skipping line 133972: expected 2 fields, saw 3
Skipping line 137850: expected 2 fields, saw 3
Skipping line 138836: expected 2 fields, saw 3
Skipping line 140154: expected 2 fields, saw 5
Skipping line 141134: expected 2 fields, saw 3
Skipping line 141140: expected 2 fields, saw 4
Skipping line 141144: expected 2 fields, saw 5
Skipping line 141148: expected 2 fields, saw 3

  df = pd.read_csv("/content/sample_data/Orca_Math_Problems.csv", on_bad_lines='warn')

ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.

In [10]:
df = pd.read_csv("/content/sample_data/Orca_Math_Problems.csv", engine='python', on_bad_lines='warn', quotechar='"')

/tmp/ipython-input-10-1215698588.py:1: ParserWarning: Skipping line 24450: ',' expected after '"'

  df = pd.read_csv("/content/sample_data/Orca_Math_Problems.csv", engine='python', on_bad_lines='warn', quotechar='"')
/tmp/ipython-input-10-1215698588.py:1: ParserWarning: Skipping line 35480: ',' expected after '"'

  df = pd.read_csv("/content/sample_data/Orca_Math_Problems.csv", engine='python', on_bad_lines='warn', quotechar='"')
/tmp/ipython-input-10-1215698588.py:1: ParserWarning: Skipping line 36467: ',' expected after '"'

  df = pd.read_csv("/content/sample_data/Orca_Math_Problems.csv", engine='python', on_bad_lines='warn', quotechar='"')
/tmp/ipython-input-10-1215698588.py:1: ParserWarning: Skipping line 96806: ',' expected after '"'

  df = pd.read_csv("/content/sample_data/Orca_Math_Problems.csv", engine='python', on_bad_lines='warn', quotechar='"')
/tmp/ipython-input-10-1215698588.py:1: ParserWarning: Skipping line 104122: ',' expected after '"'

  df = pd.read_csv("/content/sample_data/Orca_Math_Problems.csv", engine='python', on_bad_lines='warn', quotechar='"')
/tmp/ipython-input-10-1215698588.py:1: ParserWarning: Skipping line 138854: ',' expected after '"'

  df = pd.read_csv("/content/sample_data/Orca_Math_Problems.csv", engine='python', on_bad_lines='warn', quotechar='"')
/tmp/ipython-input-10-1215698588.py:1: ParserWarning: Skipping line 141152: ',' expected after '"'

  df = pd.read_csv("/content/sample_data/Orca_Math_Problems.csv", engine='python', on_bad_lines='warn', quotechar='"')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 0: invalid continuation byte

In [11]:
df = pd.read_csv(
    "/content/sample_data/Orca_Math_Problems.csv",
    engine='python',
    encoding='ISO-8859-1',   # or try 'latin1' (they are interchangeable)
    on_bad_lines='warn',
    quotechar='"'
)

/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 24450: ',' expected after '"'

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 35480: ',' expected after '"'

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 36467: ',' expected after '"'

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 96806: ',' expected after '"'

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 104122: ',' expected after '"'

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 138854: ',' expected after '"'

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 141152: ',' expected after '"'

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 161657: ',' expected after '"'

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 3821: Expected 2 fields in line 3821, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 6159: Expected 2 fields in line 6159, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 9430: Expected 2 fields in line 9430, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 14517: Expected 2 fields in line 14517, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 18565: Expected 2 fields in line 18565, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 23608: Expected 2 fields in line 23608, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 35603: Expected 2 fields in line 35603, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 35604: Expected 2 fields in line 35604, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 36573: Expected 2 fields in line 36573, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 36579: Expected 2 fields in line 36579, saw 4

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 45491: Expected 2 fields in line 45491, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 53487: Expected 2 fields in line 53487, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 61314: Expected 2 fields in line 61314, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 70088: Expected 2 fields in line 70088, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 80945: Expected 2 fields in line 80945, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 90507: Expected 2 fields in line 90507, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 95051: Expected 2 fields in line 95051, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 96018: Expected 2 fields in line 96018, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 96904: Expected 2 fields in line 96904, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 98733: Expected 2 fields in line 98733, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 101483: Expected 2 fields in line 101483, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 104181: Expected 2 fields in line 104181, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 108689: Expected 2 fields in line 108689, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 117735: Expected 2 fields in line 117735, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 120426: Expected 2 fields in line 120426, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 123985: Expected 2 fields in line 123985, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 127558: Expected 2 fields in line 127558, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 129370: Expected 2 fields in line 129370, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 134029: Expected 2 fields in line 134029, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 137903: Expected 2 fields in line 137903, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 140191: Expected 2 fields in line 140191, saw 5

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 141169: Expected 2 fields in line 141169, saw 4

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 141171: Expected 2 fields in line 141171, saw 5

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 141173: Expected 2 fields in line 141173, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 160696: Expected 2 fields in line 160696, saw 4

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 161658: Expected 2 fields in line 161658, saw 4

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 163318: Expected 2 fields in line 163318, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 166232: Expected 2 fields in line 166232, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 167785: Expected 2 fields in line 167785, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 172523: Expected 2 fields in line 172523, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 174101: Expected 2 fields in line 174101, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 175671: Expected 2 fields in line 175671, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 177282: Expected 2 fields in line 177282, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 185112: Expected 2 fields in line 185112, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 188285: Expected 2 fields in line 188285, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 192986: Expected 2 fields in line 192986, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 195342: Expected 2 fields in line 195342, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 199828: Expected 2 fields in line 199828, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 202175: Expected 2 fields in line 202175, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 208535: Expected 2 fields in line 208535, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 212507: Expected 2 fields in line 212507, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 214020: Expected 2 fields in line 214020, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 217090: Expected 2 fields in line 217090, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 231102: Expected 2 fields in line 231102, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 233381: Expected 2 fields in line 233381, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 243767: Expected 2 fields in line 243767, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 245251: Expected 2 fields in line 245251, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 250546: Expected 2 fields in line 250546, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 252133: Expected 2 fields in line 252133, saw 3

  df = pd.read_csv(
/tmp/ipython-input-11-123488665.py:1: ParserWarning: Skipping line 256758: Expected 2 fields in line 256758, saw 3

  df = pd.read_csv(

In [12]:
df.shape

(317749, 2)

In [13]:
df.head()

,question,answer
0,Jungkook is the 5th place. Find the number of ...,"If Jungkook is in 5th place, then 4 people cro..."
1,A number divided by 10 is 6. Yoongi got the re...,"Let's call the certain number ""x"". According t..."
2,Dongju selects a piece of paper with a number ...,To find the second smallest and third smallest...
3,"You wanted to subtract 46 from a number, but y...",If you accidentally subtracted 59 instead of 4...
4,The length of one span of Jinseo is about 12 c...,If one span of Jinseo is about 12 centimeters ...

In [14]:
df.tail(10)

,question,answer
317739,"The total cost of a pair of pants and a belt, ...",Let's denote the original price of the belt as...
317740,If 3.5 pounds of ground beef costs 9.77 dollar...,"First, we need to find the cost per pound for ..."
317741,A rectangular field has a length that is 3 met...,Let's denote the width of the field as \( w \)...
317742,A total of 600 tickets were sold for the schoo...,Let's denote the number of adult tickets sold ...
317743,A bottle of wine with a cork costs 2.10 dollar...,Let's denote the price of the cork as \( C \)....
317744,"Adult tickets for a show cost 6.50 dollars, wh...",Let's denote the number of adult tickets sold ...
317745,Your cell phone company offers three text-mess...,Let's denote the number of text messages as \(...
317746,Steve invests in a circus production. The cost...,"First, let's calculate the average revenue per..."
317747,Your teacher is giving a test worth 200 points...,Let's denote the number of 5-point questions a...
317748,A plane flying with a tailwind at an altitude ...,Let's denote the plane's airspeed (the speed o...

In [17]:
def extract_final_answer(text):
    if not isinstance(text, str):
        return ""

    # Trying to find numeric answers first
    matches = re.findall(r"[-+]?\d*\.\d+|\d+", text)
    if matches:
        return matches[-1]  # Returning last numeric match

    # If no number found, trying to get last word from the last sentence
    sentences = re.split(r"[.?!]", text)
    last_sentence = sentences[-2].strip() if len(sentences) > 1 else sentences[0].strip()
    return last_sentence.split(" ")[-1]

In [18]:
df["final_answer"] = df["answer"].apply(extract_final_answer)

In [19]:
df.columns

Index(['question', 'answer', 'final_answer'], dtype='object')

In [20]:
df.head()

,question,answer,final_answer
0,Jungkook is the 5th place. Find the number of ...,"If Jungkook is in 5th place, then 4 people cro...",4
1,A number divided by 10 is 6. Yoongi got the re...,"Let's call the certain number ""x"". According t...",45
2,Dongju selects a piece of paper with a number ...,To find the second smallest and third smallest...,804
3,"You wanted to subtract 46 from a number, but y...",If you accidentally subtracted 59 instead of 4...,56
4,The length of one span of Jinseo is about 12 c...,If one span of Jinseo is about 12 centimeters ...,24

In [21]:
df = df.iloc[:200]
df.shape

(200, 3)

In [22]:
df.to_csv("Orca_Math_Problems_With_Answers.csv", index=False)